eslint:
  config_file: style/config/.eslintrc.json
tslint:
  config_file: style/config/tslint.json
ruby:
  config_file: style/config/.rubocop.yml
stylelint:
  config_file: style/config/.stylelintrc.json
coffeescript:
  enabled: false
